# Write programs in Python using NumPy library to do the following:

In [1]:
import numpy as np

In [2]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis

In [3]:
print("Mean = ", np.mean(arr, axis = 1))

Mean =  [2. 7.]


## b. Get the indices of the sorted elements of a given array, a. B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]


In [4]:
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
indices = np.argsort(B)
print(indices)
print(np.sort(B))

[8 2 6 9 3 7 1 0 4 5]
[ 8 22 24 33 41 46 48 56 78 91]


## c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of the array and then reshape it into nxm array, n and m are user inputs given at the run time.

In [5]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
arr.shape

(2, 5)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.dtype

dtype('int32')

In [10]:
n = int(input("Enter no. rows = "))
m = int(input("Enter no. cols = "))
arr.reshape(n,m)

Enter no. rows = 5
Enter no. cols = 2


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of these elements in three separate arrays.

In [12]:
import numpy as np
arr=np.array([[np.nan,0],[7,70],[8,np.nan]])
print(np.where(np.isnan(arr1)))
print(np.where(arr1==0))
print(np.where(arr1!=0))

(array([0, 2], dtype=int64), array([0, 1], dtype=int64))
(array([0], dtype=int64), array([1], dtype=int64))
(array([0, 1, 1, 2, 2], dtype=int64), array([0, 0, 1, 0, 1], dtype=int64))
